#!/usr/bin/env bash
set -euo pipefail

SCRIPT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PROJECT_ROOT=${PROJECT_ROOT:-$SCRIPT_ROOT}
RL_ROOT=$(dirname "$PROJECT_ROOT")
VENDOR_ROOT=${VENDOR_ROOT:-}
ROLLOUT_ENV=${ROLLOUT_ENV:-}
TRAIN_ENV=${TRAIN_ENV:-}
ROLLOUT_PYTHON=${ROLLOUT_PYTHON:-$ROLLOUT_ENV/bin/python}
ROLLOUT_SWIFT_CLI=${ROLLOUT_SWIFT_CLI:-$ROLLOUT_ENV/bin/swift}
TRAIN_PYTHON=${TRAIN_PYTHON:-$TRAIN_ENV/bin/python}
TRAIN_SWIFT_CLI=${TRAIN_SWIFT_CLI:-$TRAIN_ENV/bin/swift}

VLLM_SERVER_HOST=${VLLM_SERVER_HOST:-127.0.0.1}
VLLM_SERVER_PORT=${VLLM_SERVER_PORT:-8000}
VLLM_SERVER_GROUP_PORT=${VLLM_SERVER_GROUP_PORT:-51216}
VLLM_SERVER_TIMEOUT=${VLLM_SERVER_TIMEOUT:-600}

export PROJECT_ROOT RL_ROOT VENDOR_ROOT
export ROLLOUT_ENV ROLLOUT_PYTHON ROLLOUT_SWIFT_CLI
export TRAIN_ENV TRAIN_PYTHON TRAIN_SWIFT_CLI
export VLLM_SERVER_HOST VLLM_SERVER_PORT VLLM_SERVER_GROUP_PORT VLLM_SERVER_TIMEOUT
if [[ -n "$TRAIN_ENV" ]]; then
  export CUDA_HOME=${CUDA_HOME:-$TRAIN_ENV}
  export CPATH=$TRAIN_ENV/targets/x86_64-linux/include${CPATH:+:$CPATH}
  export LIBRARY_PATH=$TRAIN_ENV/targets/x86_64-linux/lib${LIBRARY_PATH:+:$LIBRARY_PATH}
  export LD_LIBRARY_PATH=$TRAIN_ENV/targets/x86_64-linux/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
fi
export COLOREASON_RL_ROOT=$PROJECT_ROOT
export COLOREASON_SCHEMA_DIR=${COLOREASON_SCHEMA_DIR:-$PROJECT_ROOT/schemas}
export COLOREASON_EMBEDDING_MODEL=${COLOREASON_EMBEDDING_MODEL:-$PROJECT_ROOT/models/Qwen3-Embedding-0.6B}
export COLOREASON_EMBEDDING_MAX_LENGTH=${COLOREASON_EMBEDDING_MAX_LENGTH:-8192}
export COLOREASON_EMBEDDING_BATCH_SIZE=${COLOREASON_EMBEDDING_BATCH_SIZE:-8}
export COLOREASON_MAX_COMPLETION_TOKENS=${COLOREASON_MAX_COMPLETION_TOKENS:-32768}
if [[ -n "$VENDOR_ROOT" ]]; then
  export PYTHONPATH=$PROJECT_ROOT:$VENDOR_ROOT${PYTHONPATH:+:$PYTHONPATH}
else
  export PYTHONPATH=$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}
fi

source "$PROJECT_ROOT/configs/paper.env"
source "$PROJECT_ROOT/configs/curriculum.env"
